language: node_js
node_js:
  - v6
script:
  - npm run lint && npm test -- --coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
